pipeline {
    options { timestamps() }

    agent any
    stages {
        stage('Check scm') {
            agent any
            steps {
                checkout scm
            }
        }
        stage('Build'){
            steps {
                echo "Building ...${BUILD_NUMBER}"
                echo "Build completed"
            }
        }
        stage('Test') {
            agent { docker { image 'alpine'
                    args '-u=\"root\"'
                    }
                  }
            steps {
                sh 'apk add --update python3 py-pip'
                sh 'pip install Flask'
                sh 'pip install xmlrunner'
                sh 'python3 Lab3/test.py'
            } 
            post {
                always {
                    junit 'test-reports/*.xml'
                }   
                success {
                    echo "Application testing successfully completed "
                }
                failure {
                    echo "Ooooppss!!! Tests failed!"
                }
            }     
        }
        stage ('Docker') {
             steps {
                script {               
                    sh "docker build -t app.py -f Dockerfile ."  
                    withCredentials([string(credentialsId: 'DockJenk', variable: 'DOCKERHUB_CREDENTIALS_PSW')]) {
                        sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u haktoid --password-stdin'
                    }                                  
                    sh "docker push app.py"
                }
            }
        }
    }
}